### ISSUE TITLE
In der PDF ist hier noch ein Encoding-Problem mit den Anführungszeichen. Ist das schon gefixt?

### ISSUE THREAD

**Issue by LordEphidel** [TheOneric/ExPIIIb#13]
https://github.com/TheOneric/ExPIIIb/blob/5965d1fb3a045748a9999949edacce980358f973/EPIIIb-FS.tex#L199

**Comment by TheOneric** [comment]
Was ist denn das Problem. Soweit ich sehe werden im pdf des 5965dif commits immer automatisch die richtigen (deutschen) Anführungszeichen oben oder unten gesetzt (csquotes + \MakeOuterQutes)

**Comment by LordEphidel** [comment]
Die Version, die ich gerade vor mir hatte, hatte aus "s ein ß und aus "u ein ü gemacht.... Aber das muss woanders gewesen sein.... ':)

**Comment by LordEphidel** [comment]
Tatsächlich passiert das in meinem Branch. Da fehlt vermutlich die Änderung, die du im letzten Commit vorgenommen hast?

**Comment by TheOneric** [comment]
Das Anführungszeichen wird von Babel(?) auch verwendet um Sonderzeichen zu erzeugen. Aber das \MakeOuterQuote{"} sollte das überschreiben.
Das war ja auch der Hauptinhalt des 5965d1f commits

**Comment by TheOneric** [comment]
Ja kannst den commit ja cherry-picken
